# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demerit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(default=datetime.datetime.now)),
                ('assigned_by', models.CharField(max_length=50)),
                ('infraction', models.CharField(max_length=200)),
                ('demerit_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('parent_approval', models.BooleanField(default=False)),
                ('parent_approval_date', models.DateField(default=datetime.datetime.now)),
                ('demerit', models.ManyToManyField(to='detention.Demerit')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('security_question', models.CharField(choices=[('1', 'What is the name of the street you grew up on?'), ('2', 'What is the name of your childhood best friend?'), ('3', 'What is the name of your first pet?')], max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('security_question', models.CharField(choices=[('1', 'What is the name of the street you grew up on?'), ('2', 'What is the name of your childhood best friend?'), ('3', 'What is the name of your first pet?')], max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('1', '09'), ('2', '10'), ('3', '11'), ('4', '12')], max_length=2)),
                ('advisor', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='student_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detention.StudentProfile'),
        ),
        migrations.AddField(
            model_name='detention',
            name='parent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detention.ParentProfile'),
        ),
        migrations.AddField(
            model_name='demerit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detention.StudentProfile'),
        ),
    ]
