# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detention', '0002_auto_20170309_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detention',
            name='demerit',
        ),
        migrations.AlterField(
            model_name='detention',
            name='parent_approval_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
